version: "3"
services:
  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - renderer
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  renderer:
    build: 
      context: .
    environment: # list the models you want to track here
      MODELS=juno-x,tr-8
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.render.schedule: "@every 3m"
      ofelia.job-exec.render.command: "python /render.py"
      ofelia.job-exec.render.no-overlap: true
    volumes:
    - ./content:/content

  http_server:
    image: nginx
    depends_on:
      - renderer
    volumes:
    - ./content:/usr/share/nginx/html
    ports:
    - 8080:80

