name: python tests

on: [push]

jobs:
  test-python:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python_version'
      - name: Install Requirements
        run: python -m pip install -r requirements.txt
      - name: Run Tests
        run: python -m unittest discover tests
