name: python tests

on: [push]

jobs:
  test-python:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
      - name: Run tests
        run: python -m unittest discover tests
