name: python

on: [push]

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python_version'
          cache: 'pip'
      - name: Install Requirements
        run: python -m pip install -r requirements.txt

      - name: Run Tests
        run: python -m unittest discover tests